# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/cache@v2
      name: Cache cachetest dir
      with:
        path: out.txt
        key: ${{ matrix.python-version }}-outtxt
    - name: create file in subdir
      run: |
        ls -al
        if [ -f out.txt ]; then cat out.txt; fi
        echo "in out.txt: $GITHUB_JOB" > out.txt
