# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/cache@v2
      name: Cache cachetest dir
      with:
        path: cachetest
        key: ${{ matrix.python-version }}-cachetestdir
    - name: create file in subdir
      run: |
        echo "Listing and creating the cachetest dir"
        cat "cachetest/out.txt"
        mkdir -p cachetest
        echo "in out.txt: $GITHUB_JOB" > cachetest/out.txt
